### ISSUE TITLE
Can't add and use lit-loader in own project:

### ISSUE THREAD

**Issue by dementor5** [PolymerX/lit-loader#49]
To reproduce it:
```
➜  git clone https://github.com/PolymerX/lit-loader-example.git && cd lit-loader-element && yarn && yarn remove lit-loader && yarn add lit-loader && yarn build
yarn install v1.17.3
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > babel-loader@7.1.5" has unmet peer dependency "babel-core@6".
[5/5] Building fresh packages...
Done in 3.70s.
yarn remove v1.17.3
[1/2] Removing module lit-loader...
[2/2] Regenerating lockfile and installing missing dependencies...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
warning " > babel-loader@7.1.5" has unmet peer dependency "babel-core@6".
success Uninstalled packages.
Done in 2.97s.
yarn add v1.17.3
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > babel-loader@7.1.5" has unmet peer dependency "babel-core@6".
[5/5] Building fresh packages...
success Saved lockfile.
success Saved 27 new dependencies.
info Direct dependencies
└─ lit-loader@0.1.0
info All dependencies
├─ @babel/parser@7.5.5
├─ @babel/plugin-proposal-object-rest-spread@7.5.5
├─ ast-types@0.11.7
├─ browserslist@4.6.6
├─ caniuse-lite@1.0.30000985
├─ core-js-compat@3.1.4
├─ core-js-pure@3.1.4
├─ cosmiconfig@4.0.0
├─ electron-to-chromium@1.3.200
├─ flow-parser@0.103.0
├─ has-symbols@1.0.0
├─ import-cwd@2.1.0
├─ import-from@2.1.0
├─ is-directory@0.3.1
├─ jscodeshift@0.6.2
├─ lit-loader@0.1.0
├─ node-dir@0.1.17
├─ node-modules-regexp@1.0.0
├─ node-releases@1.1.26
├─ object.assign@4.1.0
├─ parse5@5.1.0
├─ pirates@4.0.1
├─ postcss-load-config@2.0.0
├─ recast@0.16.2
├─ require-from-string@2.0.2
├─ source-map-support@0.5.12
└─ temp@0.8.3
Done in 5.52s.
yarn run v1.17.3
$ webpack
Hash: 2e50d27a4f13d42b9c67
Version: webpack 4.16.1
Time: 346ms
Built at: 07/25/2019 12:20:54 PM
     Asset       Size  Chunks             Chunk Names
 bundle.js    128 KiB       0  [emitted]  main
index.html  334 bytes          [emitted]
[0] ./src/index.js 66 bytes {0} [built]
[1] ./src/app.js 379 bytes {0} [built]
    + 18 hidden modules

ERROR in ./src/components/CounterElement.lit
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module 'babel-core'
Require stack:
- /home/user/Projects/lit-loader-example/node_modules/babel-loader/lib/index.js
- /home/user/Projects/lit-loader-example/node_modules/loader-runner/lib/loadLoader.js
- /home/user/Projects/lit-loader-example/node_modules/loader-runner/lib/LoaderRunner.js
- /home/user/Projects/lit-loader-example/node_modules/webpack/lib/NormalModule.js
- /home/user/Projects/lit-loader-example/node_modules/webpack/lib/NormalModuleFactory.js
- /home/user/Projects/lit-loader-example/node_modules/webpack/lib/Compiler.js
- /home/user/Projects/lit-loader-example/node_modules/webpack/lib/webpack.js
- /home/user/Projects/lit-loader-example/node_modules/webpack-cli/bin/convert-argv.js
- /home/user/Projects/lit-loader-example/node_modules/webpack-cli/bin/cli.js
- /home/user/Projects/lit-loader-example/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (/home/user/Projects/lit-loader-example/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/user/Projects/lit-loader-example/node_modules/babel-loader/lib/index.js:3:13)
    at Module._compile (/home/user/Projects/lit-loader-example/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (/home/user/Projects/lit-loader-example/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at loadLoader (/home/user/Projects/lit-loader-example/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/home/user/Projects/lit-loader-example/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/home/user/Projects/lit-loader-example/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/home/user/Projects/lit-loader-example/node_modules/webpack/lib/NormalModule.js:263:3)
    at NormalModule.build (/home/user/Projects/lit-loader-example/node_modules/webpack/lib/NormalModule.js:410:15)
    at Compilation.buildModule (/home/user/Projects/lit-loader-example/node_modules/webpack/lib/Compilation.js:616:10)
    at /home/user/Projects/lit-loader-example/node_modules/webpack/lib/Compilation.js:857:14
    at /home/user/Projects/lit-loader-example/node_modules/webpack/lib/NormalModuleFactory.js:405:6
    at /home/user/Projects/lit-loader-example/node_modules/webpack/lib/NormalModuleFactory.js:155:13
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/home/user/Projects/lit-loader-example/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at /home/user/Projects/lit-loader-example/node_modules/webpack/lib/NormalModuleFactory.js:138:29
    at /home/user/Projects/lit-loader-example/node_modules/webpack/lib/NormalModuleFactory.js:342:9
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
 @ ./src/app.js 5:0-41
 @ ./src/index.js
Child html-webpack-plugin for "index.html":
     1 asset
    [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html 571 bytes {0} [built]
    [2] (webpack)/buildin/global.js 489 bytes {0} [built]
    [3] (webpack)/buildin/module.js 497 bytes {0} [built]
        + 1 hidden module
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Ok. Then:
```
➜  lit-loader-example git:(master) ✗ yarn remove babel-loader && yarn add babel-loader && yarn build
yarn remove v1.17.3
[1/2] Removing module babel-loader...
[2/2] Regenerating lockfile and installing missing dependencies...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
success Uninstalled packages.
Done in 2.76s.
yarn add v1.17.3
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ babel-loader@8.0.6
info All dependencies
└─ babel-loader@8.0.6
Done in 2.76s.
yarn run v1.17.3
$ webpack
(node:12799) UnhandledPromiseRejectionWarning: SyntaxError: super() is only valid inside a class constructor of a subclass. Maybe a typo in the method name ('constructor') or not extending another class? (13:6)
    at Object.raise (/home/user/Projects/lit-loader-example/node_modules/@babel/parser/lib/index.js:6325:17)
    at Object.parseExprAtom (/home/user/Projects/lit-loader-example/node_modules/@babel/parser/lib/index.js:8667:16)
    at Object.parseExprAtom (/home/user/Projects/lit-loader-example/node_modules/@babel/parser/lib/index.js:460:22)
    at Object.parseExprAtom (/home/user/Projects/lit-loader-example/node_modules/@babel/parser/lib/index.js:3601:20)
    at Object.parseExprSubscripts (/home/user/Projects/lit-loader-example/node_modules/@babel/parser/lib/index.js:8412:23)
    at Object.parseMaybeUnary (/home/user/Projects/lit-loader-example/node_modules/@babel/parser/lib/index.js:8392:21)
    at Object.parseExprOps (/home/user/Projects/lit-loader-example/node_modules/@babel/parser/lib/index.js:8267:23)
    at Object.parseMaybeConditional (/home/user/Projects/lit-loader-example/node_modules/@babel/parser/lib/index.js:8240:23)
    at Object.parseMaybeAssign (/home/user/Projects/lit-loader-example/node_modules/@babel/parser/lib/index.js:8187:21)
    at Object.parseExpression (/home/user/Projects/lit-loader-example/node_modules/@babel/parser/lib/index.js:8135:23)
    at Object.parseStatementContent (/home/user/Projects/lit-loader-example/node_modules/@babel/parser/lib/index.js:9958:23)
    at Object.parseStatement (/home/user/Projects/lit-loader-example/node_modules/@babel/parser/lib/index.js:9829:17)
    at Object.parseBlockOrModuleBlockBody (/home/user/Projects/lit-loader-example/node_modules/@babel/parser/lib/index.js:10405:25)
    at Object.parseBlockBody (/home/user/Projects/lit-loader-example/node_modules/@babel/parser/lib/index.js:10392:10)
    at Object.parseBlockBody (/home/user/Projects/lit-loader-example/node_modules/@babel/parser/lib/index.js:424:11)
    at Object.parseBlock (/home/user/Projects/lit-loader-example/node_modules/@babel/parser/lib/index.js:10376:10)
    at Object.parseFunctionBody (/home/user/Projects/lit-loader-example/node_modules/@babel/parser/lib/index.js:9424:24)
    at Object.parseFunctionBody (/home/user/Projects/lit-loader-example/node_modules/@babel/parser/lib/index.js:472:11)
    at Object.parseFunctionBodyAndFinish (/home/user/Projects/lit-loader-example/node_modules/@babel/parser/lib/index.js:9394:10)
    at Object.parseMethod (/home/user/Projects/lit-loader-example/node_modules/@babel/parser/lib/index.js:9348:10)
    at Object.parseMethod (/home/user/Projects/lit-loader-example/node_modules/@babel/parser/lib/index.js:479:22)
    at Object.pushClassMethod (/home/user/Projects/lit-loader-example/node_modules/@babel/parser/lib/index.js:431:10)
    at Object.parseClassMemberWithIsStatic (/home/user/Projects/lit-loader-example/node_modules/@babel/parser/lib/index.js:10729:12)
    at Object.parseClassMember (/home/user/Projects/lit-loader-example/node_modules/@babel/parser/lib/index.js:10668:10)
    at /home/user/Projects/lit-loader-example/node_modules/@babel/parser/lib/index.js:10623:14
    at Object.withTopicForbiddingContext (/home/user/Projects/lit-loader-example/node_modules/@babel/parser/lib/index.js:9702:14)
    at Object.parseClassBody (/home/user/Projects/lit-loader-example/node_modules/@babel/parser/lib/index.js:10600:10)
    at Object.parseClass (/home/user/Projects/lit-loader-example/node_modules/@babel/parser/lib/index.js:10574:22)
    at Object.parseExportDefaultExpression (/home/user/Projects/lit-loader-example/node_modules/@babel/parser/lib/index.js:10999:19)
    at Object.parseExport (/home/user/Projects/lit-loader-example/node_modules/@babel/parser/lib/index.js:10905:31)
(node:12799) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12799) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 2.10s.
```

**Comment by LasaleFamine** [comment]
Hi @dementor5, sorry for the late response. 
The lit-loader must be updated I think, for working with new version of webpack. I'm currently on holiday, I will try to update everything asap as I came back. 
Thank you for using it btw!
